### ISSUE TITLE
It lacks _ in tsugi

### ISSUE THREAD

**Issue by albsierra** [KA226-COVID/codetest#13]
https://github.com/KA226-COVID/tsugi/blob/b570c9d036922c46c934ee1de4984aa0f86cfc82/settings/key/index.php#L12

In internationalization function, it lacks a _, but I can't add the issue in the tsugi repository,

**Comment by brdebr** [comment]
I don't understand what's the problem there,
But I activated the issues at the [KA226-COVID/tsugi](https://github.com/KA226-COVID/tsugi) fork

**Comment by albsierra** [comment]
It's a problem in Tsugi's code that throws an exception when `( $CFG->providekeys === false || $CFG->owneremail === false )`.
It mus be `__(` instead `_(`
