### ISSUE TITLE
Removing grade method?

### ISSUE THREAD

**Issue by albsierra** [KA226-COVID/codetest#16]
I think that, instead remove the call to grade() method in [this commit](https://github.com/KA226-COVID/codetest/commit/1d8c88db31433bf5150a1e905143c65146847cdd#diff-1e78f863e05bb7be91fa7fdc6cb6b4384f6827e62ac68a97576236467424af4f), it would be better put next code in the grade() method:

```
    $answerOutput = null;
    if($answerLanguage == 0) {
        $client = HttpClient::create();
    
        $response = $client->request("POST", "{$CFG->apiConfigs['xml-validator']['baseUrl']}eval", [
            'json' => [
                'date' => date("c"),
                'program' => $answerText,
                'learningObject' => $exercise1->getAkId() //$exerciseId
            ]
        ]);
        $answerOutput = $response->getContent();
    }

```
The code above is currently in [actions/AnswerExercise.php](https://github.com/KA226-COVID/codetest/blob/1d8c88db31433bf5150a1e905143c65146847cdd/actions/AnswerExercise.php#L30).

Even, the code correspondent to the request could be a method in dao/CT_DAO.php, because it's there where we manage external services, and be called from dao/CT_Exercise.php.

The pregrade() method in [dao/CT_Exercise.php](https://github.com/KA226-COVID/codetest/blob/1d8c88db31433bf5150a1e905143c65146847cdd/dao/CT_Exercise.php#L384) could be removed because it's an action that can be done by validator.

**Comment by brdebr** [comment]
This was fixed at 1d8c88db31433bf5150a1e905143c65146847cdd
