### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by albsierra** [KA226-COVID/codetest#21]
https://github.com/KA226-COVID/codetest/blob/36bfeccfebb5c91788e0bcb7d15fe247e0caca6b/config_dist.php#L43

I get the error message: SSL certificate problem: unable to get local issuer certificate for "https://fgpe.dcc.fc.up.pt/api/auth/login"` when I deploy the containers and I request codetest from Moodle.

I think that the certificate is served by GEANT and it isn't a valid certificate inside the tsugi_codetest_container. I've tried set the certificate into /usr/lib/ssl/certs folder without success.

Anyone knows how to solve?

**Comment by zub4t** [comment]
I'm going to look for José Paiva to help solve it.

Regards, Marco Primo.
________________________________
De: Alberto Sierra ***@***.***>
Enviado: quinta-feira, 24 de fevereiro de 2022 11:00
Para: KA226-COVID/codetest ***@***.***>
Cc: Marco Augusto ***@***.***>; Assign ***@***.***>
Assunto: [KA226-COVID/codetest] SSL certificate problem (Issue #21)


https://github.com/KA226-COVID/codetest/blob/36bfeccfebb5c91788e0bcb7d15fe247e0caca6b/config_dist.php#L43

I get the error message: SSL certificate problem: unable to get local issuer certificate for "https://fgpe.dcc.fc.up.pt/api/auth/login"`<https://fgpe.dcc.fc.up.pt/api/auth/login%22%60> when I deploy the containers and I request codetest from Moodle.

I think that the certificate is served by GEANT and it isn't a valid certificate inside the tsugi_codetest_container. I've tried set the certificate into /usr/lib/ssl/certs folder without success.

Anyone knows how to solve?

**Comment by zpleal** [comment]
This is probably due to a sloppy certificate configuration from our sysadmin. The certificate works on browsers since they store issuer certificates but not with libraries that use certificates. He is currently fixing this issue.

**Comment by zpleal** [comment]
It should be fixed now. Could you please confirm if it works in Tsugi?

**Comment by albsierra** [comment]
Yes. it works.
Thanks.
