### ISSUE TITLE
Choose the correct validator

### ISSUE THREAD

**Issue by albsierra** [KA226-COVID/codetest#23]
https://github.com/KA226-COVID/codetest/blob/6674fef1a422f2c64cc3e7ba0d21fcbe5c085fd2/actions/AnswerExercise.php#L35

XML-validator can't be hardcoded as validator. The validator must be choose from the combobox in the student view.

**Comment by albsierra** [comment]
I saw that the url get it from [.env.example](https://github.com/KA226-COVID/deploy_docker/blob/000236e3dc44292d16c976fdf44e093808f83206/.env.example#L28) and it has java-validator as value:
`XML_EVALUATOR_URL=java-validator`
but I suposse is not a rigth way to asign.

**Comment by frasese** [comment]
Added new feature https://github.com/KA226-COVID/codetest/commit/213dd348e06969cd7d3edd1a83dd428b2b252246
