### ISSUE TITLE
Error creating exercise

### ISSUE THREAD

**Issue by albsierra** [KA226-COVID/codetest#24]
https://github.com/KA226-COVID/codetest/blob/6674fef1a422f2c64cc3e7ba0d21fcbe5c085fd2/dao/CT_Test.php#L107

If we leave **hint** input empty when we create a new exercise, that code throws an exception. However, the exercise is created.

**Comment by albsierra** [comment]
It also occurs when **exercise_language is empty**. That happens importing from context.

**Comment by frasese** [comment]
Solved in https://github.com/KA226-COVID/codetest/pull/27
