### ISSUE TITLE
Include studentID in evaluator call

### ISSUE THREAD

**Issue by albsierra** [KA226-COVID/codetest#39]
https://github.com/KA226-COVID/codetest/blob/d1d78e5f275b5fe8ea5df4288d20d2136cec8bbb/actions/AnswerExercise.php#L35

**Comment by frasese** [comment]
Solved in [8f3328432127c586a3d5e3c9497536df45df3022](https://github.com/KA226-COVID/codetest/commit/8f3328432127c586a3d5e3c9497536df45df3022)
